### ISSUE TITLE
National ID Validation returns true when used on same numbers in a row

### ISSUE THREAD

**Issue by ShahriarKh** [ali-master/persian-tools#118]
**Describe the bug**
Numbers like `0000000000`, `1111111111`, `2222222222`, ... `9999999999` are considered valid with `verifyIranianNationalId()`!

**Expected behavior**
I'm not sure if it's a bug or we have national ids like these, but for me, it seems to be a bug.

Tested on different browsers and devices and the result is the same.
`"@persian-tools/persian-tools": "^1.7.0"`

**Comment by M0rteza-M** [comment]
I'm trying to fix the problem has been stated above.

**Comment by pooooriya** [comment]
we have same national code number in Iran due to this link 
https://www.iranjib.ir/shownews/56644/%D8%B5%D8%A7%D8%AD%D8%A8-%D8%B4%D9%85%D8%A7%D8%B1%D9%87-%DA%A9%D8%AF%D9%85%D9%84%DB%8C-%DB%B1%DB%B1%DB%B1%DB%B1%DB%B1%DB%B1%DB%B1%DB%B1%DB%B1%DB%B1-%DA%A9%DB%8C%D8%B3%D8%AA%D8%9F/

**Comment by ShahriarKh** [comment]
> we have same national code number in Iran due to this link https://www.iranjib.ir/shownews/56644/%D8%B5%D8%A7%D8%AD%D8%A8-%D8%B4%D9%85%D8%A7%D8%B1%D9%87-%DA%A9%D8%AF%D9%85%D9%84%DB%8C-%DB%B1%DB%B1%DB%B1%DB%B1%DB%B1%DB%B1%DB%B1%DB%B1%DB%B1%DB%B1-%DA%A9%DB%8C%D8%B3%D8%AA%D8%9F/

Based on this, should we consider numbers like `1111111111` valid or not?
