### ISSUE TITLE
Node 17 support

### ISSUE THREAD

**Issue by amaleky** [ali-master/persian-tools#122]
persian-tools is incompatible with node 17
```
error @persian-tools/persian-tools@3.0.1: The engine "node" is incompatible with this module. Expected version ">=10.0.0 <=16". Got "17.2.0"
```
I test it with node@17 and it seams is compatible, please just upgrade dependency

**Comment by masoudgs** [comment]
@ali-master any updates on this? its blocker somehow on our projects. I understand you may be busy but that'd be nice if you send us an update. thx

**Comment by ali-master** [comment]
I'll fix this issue up to tomorrow.

**Comment by ali-master** [comment]
@persian-tools/persian-tools v3.1.1 published.
