### ISSUE TITLE
wordsToNumber return wrong number

### ISSUE THREAD

**Issue by AKoohnavard** [ali-master/persian-tools#143]
wrong number on over a million:

console.log(wordsToNumber("یک میلیون و دویست هزار و سیصد و پنجاه و هفت"));  // 1000200357
console.log(wordsToNumber("سه میلیارد و دویست میلیون و سیصد و پنجاه و هفت هزار و دویست و پنج")); // 3000000200000357000

but under a million returned correct number:

console.log(wordsToNumber("سیصد و پنجاه و هفت هزار و دویست و پنج")); // 357205

**Comment by ali-master** [comment]
@mediv0

**Comment by mediv0** [comment]
> @mediv0

didn't https://github.com/persian-tools/persian-tools/pull/145 solve the problem ?
