### ISSUE TITLE
verify the names of Iranian cities from a string.

### ISSUE THREAD

**Issue by ali-master** [ali-master/persian-tools#147]
Hi, I think we need to have a function in this library to verify the names of Iranian cities from a string.
example : 
`validateIranCity("تهران")  // return true `
`validateIranCity("تست")  // return false `

_Originally posted by @mohammadizanloo55 in https://github.com/persian-tools/persian-tools/issues/17#issuecomment-1032931117_

**Comment by mohammadizanloo55** [comment]
Thank you for accepting my idea
What is your advice on how to do this validation?
The idea I have in mind is to extract the list of Iranian cities from [here](https://fa.wikipedia.org/wiki/%D9%81%D9%87%D8%B1%D8%B3%D8%AA_%D8%B4%D9%87%D8%B1%D9%87%D8%A7%DB%8C_%D8%A7%DB%8C%D8%B1%D8%A7%D9%86) and store the information in an array and then check the given string with a function.
But we need to talk about how this function should perform validation

**Comment by pshaddel** [comment]
Hi @mohammadizanloo55 I think you can check this out: https://github.com/jd1378/iran-cities-json/blob/master/shahr.json
Also we have about 1245 cities in Iran and I just tested the performance with an array(without using map or hash tables) with 1245 elements and it was validating instantly so I guess iterating over array should do the work.
