### ISSUE TITLE
husky give an error when I'm commit 

### ISSUE THREAD

**Issue by mohammadizanloo55** [ali-master/persian-tools#151]
**Describe the bug**
I want to contribute to this project but husky gives me this error :
`husky - pre-commit hook exited with code 1 (error)`

**Expected behavior**
we have a problem in the `js-abbreviation-number` package 
vs code say : `Cannot find module 'js-abbreviation-number' or its corresponding type declarations.`

**Screenshots**
## error when I'm commit 
![image](https://user-images.githubusercontent.com/54350937/155396263-29a25a54-49f1-4556-b398-be40a0791780.png)

## error when `npm test` (i don't change anything just add multi files)
![image](https://user-images.githubusercontent.com/54350937/155395120-fb7db4c6-3fe1-4dab-8d2b-77a7413da0bf.png)

**Comment by ali-master** [comment]
fixed in v3.3.0-beta.1 on `develop` branch.

**Comment by moh3n9595** [comment]
@mohammadizanloo55,

You reported two different issues about your configurations and your newly added code. Use the `npm run prettier` command to fix the code styling issues. Also, use `npm i` in your `develop` branch to install the relevant dependencies.

**Comment by mohammadizanloo55** [comment]
Thank you. My suggestion is to write these points in the `CONTRIBUTING.md`  file to make it easier to contribute to the project.
