### ISSUE TITLE
toPersianChars It does not work properly

### ISSUE THREAD

**Issue by shahabbasian** [ali-master/persian-tools#208]
سلام

من میخواهم، ورودی کاربر را یکبار از toPersianChars رد کنم و با isPersian فارسی یا انگلیسی بودن ورودی رو بررسی کنم اما در بعضی کلمات فارسی که از تابع toPersianChars رد میشن isPersian دیگه اونو فارسی نمیشناسه

مثال:
```
isPersian(toPersianChars('مهدی'))     // false
isPersian(toPersianChars('شاه'))     // false
isPersian(toPersianChars('سلام'))     // true
```

**Comment by ali-master** [comment]
> سلام
> 
> من میخواهم، ورودی کاربر را یکبار از toPersianChars رد کنم و با isPersian فارسی یا انگلیسی بودن ورودی رو بررسی کنم اما در بعضی کلمات فارسی که از تابع toPersianChars رد میشن isPersian دیگه اونو فارسی نمیشناسه
> 
> مثال:
> 
> ```
> isPersian(toPersianChars('مهدی'))     // false
> isPersian(toPersianChars('شاه'))     // false
> isPersian(toPersianChars('سلام'))     // true
> ```

مرسی از گزارش مشکل

بررسی می‌کنیم و به زودی جزئیات بررسی رو همینجا منتشر میکنیم

**Comment by pshaddel** [comment]
@ali-master سلام علی جان.
من میتونم بررسی کنم این مشکل رو؟

**Comment by ali-master** [comment]
> @ali-master سلام علی جان.
> من میتونم بررسی کنم این مشکل رو؟

بله بله

**Comment by pshaddel** [comment]
تفاوت ها
```
'مهدی' => [ 1605, 1607, 1583, 1740 ]
toPersianChars('مهدی') => [ 1605, 1726, 1583, 1740 ]
```

[https://www.compart.com/en/unicode/U+06BE](https://www.compart.com/en/unicode/U+06BE)
[https://www.compart.com/en/unicode/U+0647](https://www.compart.com/en/unicode/U+0647)

علی جان. مشکل از حرف ه است. فقط من نمیدونم کدوم ه مربوط به فارسیه - یعنی الان نمیدونم باید isPersian رو اصلاح کنم که با این ه کد ۷۲۶ هم کار کنه یا اینکه تابع toPersianChars رو اصلاح کنم که با ه رو تبدیل نکنه به ۷۲۶
اینو بگی من احتمالا میتونم درستش کنم. @ali-master

**Comment by mediv0** [comment]
> تفاوت ها
> 
> ```
> 'مهدی' => [ 1605, 1607, 1583, 1740 ]
> toPersianChars('مهدی') => [ 1605, 1726, 1583, 1740 ]
> ```
> 
> https://www.compart.com/en/unicode/U+06BE https://www.compart.com/en/unicode/U+0647
> 
> علی جان. مشکل از حرف ه است. فقط من نمیدونم کدوم ه مربوط به فارسیه - یعنی الان نمیدونم باید isPersian رو اصلاح کنم که با این ه کد ۷۲۶ هم کار کنه یا اینکه تابع toPersianChars رو اصلاح کنم که با ه رو تبدیل نکنه به ۷۲۶ اینو بگی من احتمالا میتونم درستش کنم. @ali-master

مرتبط به https://github.com/persian-tools/persian-tools/issues/154

کدی که از تابع `toPersianChars` بر میگرده کد \u06d5 هست که یه فضای خالی داره این باید با \u0647 جایگذاری بشه

**Comment by mediv0** [comment]
مشکل اینجاست
https://github.com/persian-tools/persian-tools/blob/24d6cec34af1c958678b145f9140dfe141dc3b25/src/modules/toPersianChars/index.ts#L42

**Comment by mediv0** [comment]
با تغییر زیر تستا پس میشن
```js
	str = str.replace(new RegExp("([^ء-يٱ-ە]|$)ه", "g"), "ە$1");
	str = str.replace(/ە‌/g, "ە");
	// str = str.replace(/ه/g, "ھ");
```

passing tests:
![tests](https://i.imgur.com/hkoauM9.jpg)

**Comment by ali-master** [comment]
> با تغییر زیر تستا پس میشن
> 
> ```js
> 	str = str.replace(new RegExp("([^ء-يٱ-ە]|$)ه", "g"), "ە$1");
> 	str = str.replace(/ە‌/g, "ە");
> 	// str = str.replace(/ه/g, "ھ");
> ```
> 
> passing tests: ![tests](https://camo.githubusercontent.com/68ea6715cb0f2be515c69dc57e07523238c0026f152697798589781b6878fcec/68747470733a2f2f692e696d6775722e636f6d2f686b6f61754d392e6a7067)

مرسی مهدی که پیگیری و پیدا کردی باگ رو.

**Comment by pshaddel** [comment]
خیلی عالیه دم تون گرم - پس اینو فک کنم میتونید ببندید. من میرم سراغ یه ایشوی دیگه در اولین فرصت

**Comment by ali-master** [comment]
> خیلی عالیه دم تون گرم - پس اینو فک کنم میتونید ببندید. من میرم سراغ یه ایشوی دیگه در اولین فرصت


عالی، یه مرج ریکوئست باز کن و وصلش کن به همین ایشو که نسخه هم دادیم بعدش همینجا ورژنش رو اطلاع رسانی کنیم

**Comment by pshaddel** [comment]
مرج ریکوعست باز شد علی جان. دست اقا مهدی درد نکنه پیدا کرد مشکل رو

**Comment by ali-master** [comment]
> مرج ریکوعست باز شد علی جان. دست اقا مهدی درد نکنه پیدا کرد مشکل رو

عالی، خسته نباشی
سعی میکنم تا فردا یک نسخه جدید بدم
