### ISSUE TITLE
Iranian Sheba section not rendered in docs

### ISSUE THREAD

**Issue by mikoloism** [ali-master/persian-tools#210]
**Describe the bug**
i tried to fix it but can't find any docs folder or file to fixing it but i send a issue.

**Screenshots**

![image](https://user-images.githubusercontent.com/64307152/171278802-b876f61f-0171-4fd1-b39c-84da9aece7c7.png)

**Desktop (please complete the following information):**
 i don't think it is depend to my device information.

**Comment by ali-master** [comment]
Fixed in v3.4.0.

Thanks for reporting.
