### ISSUE TITLE
Webpack failed to parse source map

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [ali-master/persian-tools#226]
**Describe the bug**
Webpack compile app with following warning:
```
WARNING in ./node_modules/@persian-tools/persian-tools/build/persian-tools.esm.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '***/node_modules/@persian-tools/persian-tools/build/persian-tools.esm.js.map' file: Error: ENOENT: no such file or directory, open '***/node_modules/@persian-tools/persian-tools/build/persian-tools.esm.js.map'
```

Looks like Webpack can not find the source map file. 

**Screenshots**
![image](https://user-images.githubusercontent.com/17345129/177492928-e2da6825-413f-4e27-b365-ac2d8aadbbde.png)

**Additional context**
Produced on CRA project.
From yarn.lock:
```
react@^18.2.0:
  version "18.2.0"

react-scripts@5.0.1:
  version "5.0.1"

webpack@^5.64.4:
  version "5.73.0"

webpack-sources@^1.4.3:
  version "1.4.3"

webpack-sources@^2.2.0:
  version "2.3.1"

webpack-sources@^3.2.3:
  version "3.2.3"
```

**Comment by ali-master** [comment]
Try to install the package via npm instead and let me know if you still have the same error or not

**Comment by ali-master** [comment]
v3.4.0 just published, install it and let me know if still have the same error or not.
