### ISSUE TITLE
getBankNameFromCardNumber issue

### ISSUE THREAD

**Issue by AmirhBeigi** [ali-master/persian-tools#257]
Identify the name of the bank card based on the first few characters.

https://github.com/persian-tools/persian-tools/blob/de7e5c4964b47377d4c04f829c973f6fd23258e4/src/modules/getBankNameFromCardNumber/index.ts#L15

**Comment by ali-master** [comment]
> Identify the name of the bank card based on the first few characters.
> 
> https://github.com/persian-tools/persian-tools/blob/de7e5c4964b47377d4c04f829c973f6fd23258e4/src/modules/getBankNameFromCardNumber/index.ts#L15

The bank number should be validated to detect its name.

**Comment by AmirhBeigi** [comment]
> > Identify the name of the bank card based on the first few characters.
> > https://github.com/persian-tools/persian-tools/blob/de7e5c4964b47377d4c04f829c973f6fd23258e4/src/modules/getBankNameFromCardNumber/index.ts#L15
> 
> The bank number should be validated to detect its name.

But in this function, the card is not validated only the length of the card is checked and to identify the name of the bank, it only needs the first 6 digits.

**Comment by ali-master** [comment]
> > > Identify the name of the bank card based on the first few characters.
> > > https://github.com/persian-tools/persian-tools/blob/de7e5c4964b47377d4c04f829c973f6fd23258e4/src/modules/getBankNameFromCardNumber/index.ts#L15
> > 
> > 
> > The bank number should be validated to detect its name.
> 
> But in this function, the card is not validated only the length of the card is checked and to identify the name of the bank, it only needs the first 6 digits.

Your right, it should be fixed and the card number should be a valid number.
