### ISSUE TITLE
Compiled windows version?

### ISSUE THREAD

**Issue by rayman3003** [ali-master/persian-tools#303]
Can we have a compiled windows version of the project, in release section?

**Comment by ali-master** [comment]
Unfortunately I didn't get the point of your request.

**Comment by rayman3003** [comment]
I mean there is no **exe** file in the release section.

**Comment by mediv0** [comment]
This package meant to be used within your app not standalone such as exe etc...

**Comment by rayman3003** [comment]
It meant? Whats the meaning of that? 

It is just a request. If u don't want to accept it, just say it. 

It is no needed for using such a meaningless word such as "meant to be used"!!!
