### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ali-mozaffari** [ali-master/persian-tools#304]
the persian-tools work with browser which its default language is in English. But when I change the default language in Persian, this error occurs with persion-tools.

Error-message: "Uncaught RangeError: Maximum call stack size exceeded"

please help me for this issue.

**Comment by ali-master** [comment]
Hi there

Please provide a minimum repo to reproduce the issue

**Comment by ali-mozaffari** [comment]
Dear Ali,
here is the browser which its default language is in English:
![english-no-error](https://user-images.githubusercontent.com/103691384/218433127-f4459b97-c48c-43c5-95ab-af31b1330670.PNG)

the below are the browser which its default language is in Persian:
![persian-1](https://user-images.githubusercontent.com/103691384/218433292-7403a263-441a-4663-999f-d5527ca68553.PNG)
![persian-2](https://user-images.githubusercontent.com/103691384/218433349-236251af-d918-422b-9dc5-effe13fd2b48.PNG)

And here is the way I use in the code:

<span className="persianToolsText">
            {kiloGram && (
              <span>
                {persianTools.numberToWords(kiloGram)} <span>کیلوگرم </span>{' '}
                <span className="text-danger">در پلیگان کشت</span>
              </span>
            )}
          </span>

**Comment by ali-mozaffari** [comment]
Notice: I checked this one in variety of conditions. Then I found out that it read 3 input numbers and for 4th input the above error occurs.

**Comment by ali-master** [comment]
We should reproduce the same environment to find the bug, so we appreciate it if you create and provide a minimal repo that occurs the bug there.

**Comment by ali-mozaffari** [comment]
thank you for the response. Yesterday, I have change the library and now using another one. sorry for that, because it was forced to fix this bug as soon as possible. regardless of default Persian language for the system, you will face this bug if you enter more number about 16 or 17 in default English language of you system.

**Comment by mediv0** [comment]
> thank you for the response. Yesterday, I have change the library and now using another one. sorry for that, because it was forced to fix this bug as soon as possible. regardless of default Persian language for the system, you will face this bug if you enter more number about 16 or 17 in default English language of you system.

checked the code with `3000000000000000000000000000000000000000000000000000000000000000`  coudnt find any issues 

cant help if we can't reproduce
