### ISSUE TITLE
divide package to multi packages

### ISSUE THREAD

**Issue by mohamadrezamomeni** [ali-master/persian-tools#312]
I like this package but I question why it does everything. Is it better to split this package into several packages? like nestjs that use lerna.js for dividing packages

**Comment by ali-master** [comment]
I'll do it in holidays.

**Comment by mohamadrezamomeni** [comment]
it is honor for me to contribute to this topic if you like, we can do it together :)

**Comment by ali-master** [comment]
Great, first of all, thank you so much for your attention.
I think we should do some research on the way and do something like lodash did before.

**Comment by mohamadrezamomeni** [comment]
exactly
