### ISSUE TITLE
`phoneNumberDetail` method has incorrect typings

### ISSUE THREAD

**Issue by mhsattarian** [ali-master/persian-tools#322]
**Describe the bug**
`phoneNumberDetail` method has incorrect typings.

**Expected behavior**
`OperatorModel` in [phoneNumber/utils.ts](https://github.com/persian-tools/persian-tools/blob/05d8797ce236eea5fe082c45943f254bee6f0c4b/src/modules/phoneNumber/utils.ts#LL7C33-L7C33) should be as follows:

```ts
interface OperatorModel {
    province: string[];
    base: string;
    operator?: string;
    type: string[];
}
```

**Comment by ali-master** [comment]
Thanks for reporting, I appreciate any PR

**Comment by mhsattarian** [comment]
Welcome.
I created PR #323.
