### ISSUE TITLE
phoneNumberValidator does not support all mobile number formats

### ISSUE THREAD

**Issue by hosseinghs** [ali-master/persian-tools#325]
**Describe the bug**
I have a valid number just bought from MCI and here it is: 09963209016
phoneNumberValidator method **does not approve** this mobile number as a **valid one.**
**To Reproduce**
1. pass the mobile number 09963209016 to phoneNumberValidator function => const isValid = phoneNumberValidator(09963209016) 
2. console.log(isValid) => false

**Expected behavior**
this mobile number must be considerd as a valid mobile number

**Screenshots**
![image](https://github.com/persian-tools/persian-tools/assets/72767346/23cddca2-78a0-44f7-8c10-18f231eababe)

**Comment by AmirhBeigi** [comment]
Also, prefix **0923** is not supported

These problems have been fixed in the code but not updated in npm
The last npm update was 9 months ago

**Comment by ali-master** [comment]
We are trying to fix other issues and release a new version with significant changes such as performance improvements.

Thanks for your patience.
