### ISSUE TITLE
Wrong result of toPersianChars

### ISSUE THREAD

**Issue by ahmadi-akbar** [ali-master/persian-tools#344]
### Describe the bug
"تلفن همراه" turns to **"تلفنە مراه"**

### To Reproduce
Run this snippet
```js
import { toPersianChars } from '@persian-tools/persian-tools';
const input = 'تلفن همراه';
const output = toPersianChars(input);

console.group('toPersianChars');
console.log('input:', input);
console.log('output:', output);
console.groupEnd();
```

<img width="228" alt="image" src="https://github.com/persian-tools/persian-tools/assets/48069695/d2839264-cdff-4272-8486-55f91ea934c5">

### Expected behavior
<img width="242" alt="image" src="https://github.com/persian-tools/persian-tools/assets/48069695/ba9103b0-8f5d-4125-9a4a-e50bfd233a4f">

**Additional context**
Version: 3.5.0

**Comment by Basiiil** [comment]
This bug has not been fixed yet! @ali-master

**Comment by ali-master** [comment]
I'll try to release a new version today.

**Comment by ali-master** [comment]
Version [3.5.1](https://www.npmjs.com/package/@persian-tools/persian-tools/v/3.5.1) just released

**Comment by Basiiil** [comment]
thanks a lot I will test it
