### ISSUE TITLE
maximum call stack size excceded error 

### ISSUE THREAD

**Issue by ipharkat** [ali-master/persian-tools#358]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ali-master** [comment]
Hi there

I can't reproduce the issue. Create a repo

**Comment by elhamkarimii** [comment]
Hi there @ipharkat.

Please check out issue #365 for the response.

Thanks!
