### ISSUE TITLE
NumberToWords

### ISSUE THREAD

**Issue by Majid-Moradi** [ali-master/persian-tools#359]
In Readme wrote numberToWords but NumberToWords is correct

**Comment by moh3n9595** [comment]
Can you create a reproducible example? Seems `numberToWords` is correct ([line 10](https://github.com/persian-tools/persian-tools/blob/098c149201cef9df8a88b56e593cf8378695c378/src/index.ts#L10C1-L10C90))

**Comment by elhamkarimii** [comment]
Hi There @Majid-Moradi.

All our function names are camel case.
Therefor this is correct.

Thanks for mentioning!
